language: python
python: 2.7
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:inkscape.dev/stable
    packages:
    - wget
    - inkscape
    - libxml2-dev
    - libxslt1-dev
    - python-dev
    - zlib1g-dev
    - pkg-config
    - python-pip
    - poppler-utils
git:
  submodules: false
cache:
  directories:
  - "$HOME/.cache/pip"
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- pip install -U pip wheel
- pip install --requirement=$TRAVIS_BUILD_DIR/requirements.txt
- export PYTHONPATH=/usr/local/lib/python:/usr/share/inkscape/extensions/:$PYTHONPATH
- bash _scripts/install.sh
script:
- bash _scripts/build.sh
- bash _scripts/test.sh
deploy:
  provider: s3
  access_key_id: AKIAIDEHTMJNYP3JJWUA
  secret_access_key:
    secure: Fhm7lL3B6QTaRMu38NGsx0nDwIKxQXOgjHM5ENDhBrJCLK2X+iwpGxrpDA+rijFnQzt49ahh6hDuVvKj+li+WKpm2KwT65y7DoWx9CZE3f9s+2CxGzhbUfAiXnoVM1eaxwn5ohI1poSCk5My/epXOXX8MsZFo+YkEl3QiyPJ1qkKldqJW3ZpRoBjDQYfDr+r4UshP2YVkqlZHpfQwDrDoEabnLLsBDlD8wFZADCiRQbPYXr8Vi/LWh47q47gRlWHtzPeVJ3ZN7aEvLdYp5UOssUYTCNXBTdpvEvl7sjp/YLHEB3n4ZJs6I6GE9E+laYAny23UAk/MEhT9UwAFWzk95P2uKRIy7rbWxQ/PtPU23B+XudKS5Qy+EYNc8Tn1VpCH99McFbt0PCH4gL1jwXpTZxH+tbomizrjK/SQU8nzs+c+JyReL8apJtTmYFdzC20MX2/uD08aeg3lnNPhOy2bqdDzhbn0xquC5Rr6K2Xo7mpTsVjWFs4m0zMzXnnTwQH/BRE7bJnc4iW8B/R6yKIdkDJODJZGfNo9yv5Sip6JybvLg3Gy8SB3juIXuTpKL5T02aFNdAw4FHvnTA5O8vIjW4AxbFjMyycCAh0wsLNk78zlK00p5cD3mmfbpT+Nq6TMy1xXhiaKLbXMZYsh7UfTuN2pHr3zFmLOxk7r+JNdH0=
  bucket: static.9thcircle.it
  skip_cleanup: true
  region: eu-west-1
  local-dir: pdf.en
  upload-dir: woc-builds
  acl: public_read
  detect_encoding: true
  on:
    repo: 9thcirclegames/cthulhu-deck
    branch: master
notifications:
  slack:
    secure: FL3WihkxQyW14wXtUZ5zXKAZLUmAbJDPsLEwyArBFOfcU82JyEvfXyMCBwi6iRFHf7EDtYUF06BfuqHxL4qXO5zJuhcpqTikQltPkCom4WLINg29VdG038H2gsTGTVoUhrBC3REWeEfkXXOzL//E2dReJvHKdGoXXXEiGpD/WyGrr98e3gvXY+d21MBE6KhIAH2uaLBHD14Y8ZXo8tZZWfGnqe6c3qpdUKFci/tKTZPMqVR4+bqjdUjE5NSoU9FEoPQUnJZmXbnFGRPB+70wLayknfMkvysPi9i/FDdSW5lAenXEUJb5eKr5eseS4/hKIJ7nPucK2MY+XPt6xyEYX6DdYOcjqh8RujbsspfBqgwlizU80ISX+uunRMZ47XSUIlb6QIgcNJ+M2K+Gv6PfJnrykyjriL/mFyO3ADwUmdjQQuWWRoiiYwvzd0w4Kgv7v4A3ULzcImxXqdu8gu0qCDiGaMTi2HgXbHzBsBPGHARcL2PXpt3S9iue+itrnlbzLhjOhGzaZo+jqQBtr0l8v7TvwnlYCxhVf5keSHl/41qOakfQ123h2zIAZvJKov0pJ9Ud/DMizU4O6AIM/rngMekTba54P1rj/C2OOBvR+q5pAl4KFV5j88faDjG2VKV4/dLyXEX8G4uiREFyVCCelwzavzS6GJM1w3zdwMpGlLs=
