language: python
python: 2.7
sudo: false
addons:
  apt:
    sources:
    - sourceline: ppa:inkscape.dev/stable
    - sourceline: ppa:marutter/rrutter
    packages:
    - wget
    - inkscape
    - libxml2-dev
    - libxslt1-dev
    - python-dev
    - zlib1g-dev
    - pkg-config
    - python-pip
    - pdftk
    - r-base
    - r-base-dev
    - pandoc
    - pandoc-citeproc
    - texlive-latex-recommended
    - texlive-xetex
    - texlive-luatex
    - texlive-fonts-recommended
    - etoolbox
    - wkhtmltopdf
    - lmodern
git:
  submodules: false
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/Rlib"
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- pip install -U pip wheel
- pip install --requirement=$TRAVIS_BUILD_DIR/requirements.txt
- export PYTHONPATH=/usr/local/lib/python:/usr/share/inkscape/extensions/:$PYTHONPATH
- mkdir -p $HOME/Rlib
- echo 'R_LIBS=~/Rlib' > $HOME/.Renviron
- echo 'options(repos = "http://cran.rstudio.com")' > $HOME/.Rprofile
- echo '.travis.yml' > $HOME/.Rbuildignore
- Rscript -e 'if(!"tidyverse" %in% rownames(installed.packages())) { install.packages("tidyverse", dependencies = TRUE) }'
- Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
- bash _scripts/install.sh
script:
- bash _scripts/build.sh
- bash _scripts/test.sh
deploy:
  provider: s3
  access_key_id: AKIAIDEHTMJNYP3JJWUA
  secret_access_key:
    secure: Fhm7lL3B6QTaRMu38NGsx0nDwIKxQXOgjHM5ENDhBrJCLK2X+iwpGxrpDA+rijFnQzt49ahh6hDuVvKj+li+WKpm2KwT65y7DoWx9CZE3f9s+2CxGzhbUfAiXnoVM1eaxwn5ohI1poSCk5My/epXOXX8MsZFo+YkEl3QiyPJ1qkKldqJW3ZpRoBjDQYfDr+r4UshP2YVkqlZHpfQwDrDoEabnLLsBDlD8wFZADCiRQbPYXr8Vi/LWh47q47gRlWHtzPeVJ3ZN7aEvLdYp5UOssUYTCNXBTdpvEvl7sjp/YLHEB3n4ZJs6I6GE9E+laYAny23UAk/MEhT9UwAFWzk95P2uKRIy7rbWxQ/PtPU23B+XudKS5Qy+EYNc8Tn1VpCH99McFbt0PCH4gL1jwXpTZxH+tbomizrjK/SQU8nzs+c+JyReL8apJtTmYFdzC20MX2/uD08aeg3lnNPhOy2bqdDzhbn0xquC5Rr6K2Xo7mpTsVjWFs4m0zMzXnnTwQH/BRE7bJnc4iW8B/R6yKIdkDJODJZGfNo9yv5Sip6JybvLg3Gy8SB3juIXuTpKL5T02aFNdAw4FHvnTA5O8vIjW4AxbFjMyycCAh0wsLNk78zlK00p5cD3mmfbpT+Nq6TMy1xXhiaKLbXMZYsh7UfTuN2pHr3zFmLOxk7r+JNdH0=
  bucket: static.9thcircle.it
  skip_cleanup: true
  region: eu-west-1
  local-dir: pdf
  upload-dir: woc-builds
  acl: public_read
  detect_encoding: true
  on:
    repo: 9thcirclegames/cthulhu-deck
    branch: master
notifications:
  slack:
    secure: VADMzd4GIBncj+DmjWditmWfl6vYVJQ8vjZZ4yBgP4+7Txtew8eDxjtPuEO9ut7qmGJQR+1L1Hxc/6GRQgk+dBonz5s/eQFYnMdG59plIpIoLp7u+ua1W6MbNVPkwGhUGnFBLrsF1lwb1PUmr/eh42DOfd85zdLTwn2Jy0Oi7Xx4GoCAgvLPjXAKB7K1Qgy9XoCe9DM+QglgkvrujNkegMuHSTWYlVuZlqyHiaPUKHFEYNH0dESO0jKgaWfaLMebLTDGhPYrT9YHmoPffXnJ/o5pUOjYohAEph5gBUIfNl3zVskUhY6t6VaTtTGZV3rgtb78IQyqBPOwm00naeygVv0KP03qUKYE4qv9qOJVDodtuJo/9xUnpGO7o3s5ZqfbYxM1g5bi1KRChNWc7HjKj+KPmg+YZNLe2ZedxPRPONjg8SfKHdFKMZlb0f9139JBtRRmKT6KJsuvVAm4AtIQI8XSXm8wwPOeLqnJppIUJ9VaLFY+a2uXQkPOxEEWgwZB1oGAYpgs1KXHkwgWc01LBE5cJGQb9H59JcTFlWtahrnmkaZxG1Cnl/7Zvm4hVJntTI2MiGoWoY7HrWDA3r20wTRUgAh71sHQFCglMu1eSIHHLYN2OcVLnXTFYJHEvwRE1sznXHo3EFicdHtwawJKcKFR1EVuivxbJB+t8YjyLWQ=
